language: cpp
jobs:
  include:
    - name: Linux GCC 7
      os: linux
      dist: bionic
      compiler: gcc

    - name: Linux GCC 10
      os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-tootchain-r-test
          packages:
            - gcc-10
            - g++-10
      env: MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

    - name: Linux Clang 7
      os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          packages:
            - libc++-dev
            - libc++abi-dev

    - name: Linux Clang 10
      os: linux
      dist: focal
      compiler: clang
      addons:
        apt:
          packages:
            - clang-10
            - libc++-dev
            - libc++abi-dev
      env: MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

    - name: OSX GCC 7
      os: osx
      osx_image: xcode12.2
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"

    - name: OSX GCC 10
      os: osx
      osx_image: xcode12.2
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - MATRIX_EVAL="brew upgrade gcc && CC=gcc-10 && CXX=g++-10"

    - name: OSX Clang 9
      os: osx
      osx_image: xcode9.4
      compiler: clang

    - name: OSX Clang 12
      os: osx
      osx_image: xcode12.2
      compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"
script: make -j check_run check_run_release
