language: cpp
compiler:
  - clang
  - gcc
script: make check run
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" ; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
