language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script: make -j && make check run
install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] && [[ "$CXX" = "g++" ]] ; then export CXX="g++-6" CC="gcc-6" ; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
